version: "3.9"
services:
  db:
    image: postgres:11.11-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/john/projects/rails5/.bashrc:/root/.bashrc 
      - /home/john/projects/rails5/.bash_history:/root/.bash_history
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  ###############
  # development
  #
  # #############
  rails5:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_ENV: "development"
    # Note that you have to bind to 0.0.0.0
    command: "bundle exec rails s  -b 0.0.0.0"
    ports:
      - "3000:3000"
    # Access through browser at http://localhost:3000/
    depends_on:
      - db
      # For development, mount rails app directory
    volumes:
      - /home/john/projects/rails5/app:/rails5/app  # bind mount

volumes:
  postgres_data: {}


 
