version: "3.9"
services:
  db:
    image: postgres:11.11-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/john/projects/rails5/.bashrc:/root/.bashrc 
      - /home/john/projects/rails5/.bash_history:/root/.bash_history
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  ###############
  # production
  #
  # #############
  rails5_prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production 
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_ENV: production
    # Note that you have to bind to 0.0.0.0
    command: "bundle exec rails s  -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: {}
 
