default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_dev
  username: postgres
  password: password
  host: db


test:
  <<: *default
  database: rails5_test
  database: app_test
  username: postgres
  password: password
  host: db

production:
  <<: *default
  database: app_production
  username: postgres
  password: password
  host: db

